[template]
src = "headphones.ini.tmpl"
dest = "/srv/headphones/config/headphones.ini"
keys = [
	"/self/host/labels/depot.user",
	"/self/host/labels/depot.password",
	"/self/host/labels/depot.headphones.api_key",
	"/self/host/labels/depot.pushover.api_key"
]